services:

  traefik:
    image: traefik:v2.9
    container_name: api_gateway
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/tmp/traefik.yaml"
      - "--entrypoints.web.address=:80"
    ports:
      - "801:80"       # API Gateway
      - "8081:8080"   # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/tmp/traefik.yaml:ro
    networks:
      - airlines-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: message_broker
    ports:
      - "5672:5672"   # Message port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - airlines-net

  postgres_user:
    image: postgres:15-alpine
    container_name: db_user_service
    environment:
      POSTGRES_DB: ${POSTGRES_DB_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_user_data:/var/lib/postgresql/data
    networks:
      - airlines-net

  postgres_flight:
    image: postgres:15-alpine
    container_name: db_flight_service
    environment:
      POSTGRES_DB: ${POSTGRES_DB_FLIGHT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_flight_data:/var/lib/postgresql/data
    networks:
      - airlines-net

  postgres_booking:
    image: postgres:15-alpine
    container_name: db_booking_service
    environment:
      POSTGRES_DB: ${POSTGRES_DB_BOOKING}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_booking_data:/var/lib/postgresql/data
    networks:
      - airlines-net

  mongo_notification:
    image: mongo:6.0
    container_name: db_notification_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_notif_data:/data/db
    networks:
      - airlines-net

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - airlines-net

  # ---------------------------------------------------------------------------
  # MICROSERVICES
  # ---------------------------------------------------------------------------
  
  # 1. USER SERVICE
  user_service:
    build: ./user_service
    container_name: user_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./user_service:/app
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_user:5432/${POSTGRES_DB_USER}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres_user
    networks:
      - airlines-net

  # 2. FLIGHT SERVICE
  flight-service:
    build: ./flight_service
    container_name: flight_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./flight_service:/app
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_flight:5432/${POSTGRES_DB_FLIGHT}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/
      - SERVICE_API_KEY=${SERVICE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres_flight
    networks:
      - airlines-net

  # # 3. BOOKING SERVICE
  booking_service:
    build: ./booking_service
    container_name: booking_service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8003:8000"
    volumes:
      - ./booking_service:/app
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_booking:5432/${POSTGRES_DB_BOOKING}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/
      - FLIGHT_SERVICE_URL=${FLIGHT_SERVICE_URL}
      - SERVICE_API_KEY=${SERVICE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres_booking
      - rabbitmq
    networks:
      - airlines-net

  # 4. NOTIFICATION SERVICE
  notification_service:
    build: ./notification_service
    container_name: notification_service
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    ports:
      - "8004:8000"
    volumes:
      - ./notification_service:/app
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo_notification:27017/notification_db?authSource=admin
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongo_notification
      - rabbitmq
      - redis
    networks:
      - airlines-net

  # ---------------------------------------------------------------------------
  # FRONTEND
  # ---------------------------------------------------------------------------
  frontend:
      build:
        context: ./frontend
        args:
          # Pass the API URL to the build process
          - VITE_API_URL=${VITE_API_URL}
      container_name: react_frontend
      volumes:
        # We ONLY mount the nginx config if you want to tweak it without rebuilding.
        # We DO NOT mount the source code anymore because this is a production build.
        - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "3000:80" # Host Port 3000 -> Container Port 80
      networks:
        - airlines-net
      depends_on:
        - traefik

networks:
  airlines-net:
    driver: bridge

volumes:
  pg_user_data:
  pg_flight_data:
  pg_booking_data:
  mongo_notif_data:
  rabbitmq_data:
  redis_data: