apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: airlines
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_DB_USER: YWlybGluZXNfdXNlcg==
  POSTGRES_DB_FLIGHT: YWlybGluZXNfZmxpZ2h0
  POSTGRES_DB_BOOKING: YWlybGluZXNfYm9va2luZw==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  MONGO_INITDB_ROOT_USERNAME: bW9uZ28=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
  SECRET_KEY: c29tZV9yYW5kb21fa2V5
  SERVICE_API_KEY: c29tZV9hcGlfa2V5
  FLIGHT_SERVICE_URL: aHR0cDovL2ZsaWdodC1zZXJ2aWNlLmFpcmxpbmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjgwMDA=
  VITE_API_URL: aHR0cDovL2xvY2FsaG9zdDo4MDE=